-- ============================================================================
-- NBA (NEXT BEST ACTION) DOMAIN SCHEMA
-- Version: 1.0
-- Purpose: Store NBA action catalog, recommendations, and execution records
-- ============================================================================

-- ============================================================================
-- NBA_ACTION_CATALOG TABLE
-- Master list of available NBA actions (seed data from NBA engine)
-- ============================================================================

CREATE TABLE IF NOT EXISTS nba.nba_action_catalog (
    -- Primary Key
    action_id UUID PRIMARY KEY,

    -- Action Identification
    action_code VARCHAR(50) UNIQUE NOT NULL,
    action_name VARCHAR(200) NOT NULL,

    -- Classification
    business_issue VARCHAR(50) NOT NULL,           -- Acquire, Grow, Retain, Service
    action_category VARCHAR(50) NOT NULL,          -- Retention, Upsell, CrossSell, Service, Wellness

    -- Execution Channel
    channel VARCHAR(30) NOT NULL,                  -- Email, SMS, Phone, InApp, Letter, Web

    -- Description
    description TEXT,

    -- Rules (JSON for flexibility)
    eligibility_rules JSONB,                       -- Who can receive this action
    suitability_rules JSONB,                       -- When is it appropriate

    -- Business Value
    base_business_value DECIMAL(12,2),             -- Expected value if successful
    probability_multiplier DECIMAL(5,2) DEFAULT 1.0, -- Multiplier for behavior probability

    -- Contact Policy
    cooldown_days INTEGER DEFAULT 30,              -- Min days between same action
    max_attempts INTEGER DEFAULT 3,                -- Max times to offer to same member

    -- Status
    is_active BOOLEAN DEFAULT TRUE,

    -- Audit
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    created_by VARCHAR(50) DEFAULT 'NBA_ENGINE',

    -- Constraints
    CONSTRAINT chk_nba_catalog_business_issue CHECK (business_issue IN ('Acquire', 'Grow', 'Retain', 'Service')),
    CONSTRAINT chk_nba_catalog_action_category CHECK (action_category IN ('Retention', 'Upsell', 'CrossSell', 'Service', 'Wellness')),
    CONSTRAINT chk_nba_catalog_channel CHECK (channel IN ('Email', 'SMS', 'Phone', 'InApp', 'Letter', 'Web'))
);

-- Indexes
CREATE INDEX IF NOT EXISTS idx_nba_catalog_category ON nba.nba_action_catalog(action_category);
CREATE INDEX IF NOT EXISTS idx_nba_catalog_channel ON nba.nba_action_catalog(channel);
CREATE INDEX IF NOT EXISTS idx_nba_catalog_active ON nba.nba_action_catalog(is_active) WHERE is_active = TRUE;

-- ============================================================================
-- NBA_ACTION_RECOMMENDATION TABLE
-- Recommended actions generated by NBA engine for simulation to execute
-- ============================================================================

CREATE TABLE IF NOT EXISTS nba.nba_action_recommendation (
    -- Primary Key
    recommendation_id UUID PRIMARY KEY,

    -- Batch Identification
    batch_id UUID NOT NULL,                        -- NBA run batch identifier
    batch_date DATE NOT NULL,                      -- When batch was generated

    -- Target
    member_id UUID NOT NULL,
    policy_id UUID,

    -- Action Reference
    action_id UUID NOT NULL,

    -- Scoring (from NBA engine)
    propensity_score DECIMAL(5,4),                 -- Likelihood of response (0-1)
    urgency_score DECIMAL(5,4),                    -- Time sensitivity (0-1)
    business_value_score DECIMAL(12,2),            -- Expected value
    priority_rank INTEGER,                         -- Rank among member's actions (1 = highest)
    final_score DECIMAL(10,4),                     -- Combined score for arbitration

    -- Context
    trigger_reason VARCHAR(100),                   -- Why this action was recommended
    trigger_signals JSONB,                         -- Signals that triggered recommendation
    model_version VARCHAR(50),                     -- Which model version generated this

    -- Validity Window
    valid_from DATE NOT NULL,
    valid_until DATE NOT NULL,

    -- Status
    status VARCHAR(20) DEFAULT 'pending',          -- pending, scheduled, executed, expired, suppressed
    suppression_reason VARCHAR(100),

    -- Audit
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    modified_at TIMESTAMP WITH TIME ZONE,

    -- Foreign Keys
    CONSTRAINT fk_nba_recommendation_member FOREIGN KEY (member_id) REFERENCES policy.member(member_id),
    CONSTRAINT fk_nba_recommendation_policy FOREIGN KEY (policy_id) REFERENCES policy.policy(policy_id),
    CONSTRAINT fk_nba_recommendation_action FOREIGN KEY (action_id) REFERENCES nba.nba_action_catalog(action_id),

    -- Constraints
    CONSTRAINT chk_nba_recommendation_status CHECK (status IN ('pending', 'scheduled', 'executed', 'expired', 'suppressed')),
    CONSTRAINT chk_nba_recommendation_valid_dates CHECK (valid_until >= valid_from)
);

-- Indexes
CREATE INDEX IF NOT EXISTS idx_nba_recommendation_member ON nba.nba_action_recommendation(member_id);
CREATE INDEX IF NOT EXISTS idx_nba_recommendation_policy ON nba.nba_action_recommendation(policy_id) WHERE policy_id IS NOT NULL;
CREATE INDEX IF NOT EXISTS idx_nba_recommendation_batch ON nba.nba_action_recommendation(batch_id);
CREATE INDEX IF NOT EXISTS idx_nba_recommendation_status ON nba.nba_action_recommendation(status);
CREATE INDEX IF NOT EXISTS idx_nba_recommendation_valid ON nba.nba_action_recommendation(valid_from, valid_until);
CREATE INDEX IF NOT EXISTS idx_nba_recommendation_pending ON nba.nba_action_recommendation(status, valid_from)
    WHERE status = 'pending';

-- ============================================================================
-- NBA_ACTION_EXECUTION TABLE
-- Records of actions executed by the simulation
-- ============================================================================

CREATE TABLE IF NOT EXISTS nba.nba_action_execution (
    -- Primary Key
    execution_id UUID PRIMARY KEY,

    -- Source Recommendation
    recommendation_id UUID,

    -- Action Details
    action_id UUID NOT NULL,
    member_id UUID NOT NULL,
    policy_id UUID,

    -- Execution Details
    executed_at TIMESTAMP WITH TIME ZONE NOT NULL,
    execution_channel VARCHAR(30) NOT NULL,
    execution_method VARCHAR(50),                  -- Automated, AgentAssisted, SelfService

    -- Linked Entities (what was created as part of execution)
    communication_id UUID,
    interaction_id UUID,
    campaign_response_id UUID,

    -- Immediate Response (if applicable)
    immediate_response VARCHAR(30),                -- Delivered, Opened, Clicked, Ignored, Failed
    response_at TIMESTAMP WITH TIME ZONE,

    -- Simulation Metadata
    worker_id INTEGER,
    simulation_date DATE,

    -- Audit
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),

    -- Foreign Keys
    CONSTRAINT fk_nba_execution_recommendation FOREIGN KEY (recommendation_id)
        REFERENCES nba.nba_action_recommendation(recommendation_id),
    CONSTRAINT fk_nba_execution_action FOREIGN KEY (action_id)
        REFERENCES nba.nba_action_catalog(action_id),
    CONSTRAINT fk_nba_execution_member FOREIGN KEY (member_id) REFERENCES policy.member(member_id),
    CONSTRAINT fk_nba_execution_policy FOREIGN KEY (policy_id) REFERENCES policy.policy(policy_id),
    CONSTRAINT fk_nba_execution_communication FOREIGN KEY (communication_id)
        REFERENCES communication.communication(communication_id),
    CONSTRAINT fk_nba_execution_interaction FOREIGN KEY (interaction_id)
        REFERENCES crm.interaction(interaction_id),

    -- Constraints
    CONSTRAINT chk_nba_execution_channel CHECK (execution_channel IN ('Email', 'SMS', 'Phone', 'InApp', 'Letter', 'Web')),
    CONSTRAINT chk_nba_execution_response CHECK (immediate_response IS NULL OR
        immediate_response IN ('Delivered', 'Opened', 'Clicked', 'Ignored', 'Failed', 'Answered', 'Voicemail', 'NoAnswer'))
);

-- Indexes
CREATE INDEX IF NOT EXISTS idx_nba_execution_member ON nba.nba_action_execution(member_id);
CREATE INDEX IF NOT EXISTS idx_nba_execution_policy ON nba.nba_action_execution(policy_id) WHERE policy_id IS NOT NULL;
CREATE INDEX IF NOT EXISTS idx_nba_execution_action ON nba.nba_action_execution(action_id);
CREATE INDEX IF NOT EXISTS idx_nba_execution_date ON nba.nba_action_execution(executed_at);
CREATE INDEX IF NOT EXISTS idx_nba_execution_sim_date ON nba.nba_action_execution(simulation_date);
CREATE INDEX IF NOT EXISTS idx_nba_execution_recommendation ON nba.nba_action_execution(recommendation_id)
    WHERE recommendation_id IS NOT NULL;
CREATE INDEX IF NOT EXISTS idx_nba_execution_channel ON nba.nba_action_execution(execution_channel);

-- ============================================================================
-- VIEWS FOR ANALYTICS
-- ============================================================================

-- View: Active recommendations ready for execution
CREATE OR REPLACE VIEW nba.v_nba_pending_actions AS
SELECT
    r.recommendation_id,
    r.member_id,
    r.policy_id,
    r.action_id,
    a.action_code,
    a.action_name,
    a.action_category,
    a.channel,
    a.probability_multiplier,
    r.propensity_score,
    r.urgency_score,
    r.final_score,
    r.priority_rank,
    r.trigger_reason,
    r.valid_from,
    r.valid_until
FROM nba.nba_action_recommendation r
JOIN nba.nba_action_catalog a ON r.action_id = a.action_id
WHERE r.status = 'pending'
  AND a.is_active = TRUE
ORDER BY r.member_id, r.priority_rank;

-- View: Execution summary by action category
CREATE OR REPLACE VIEW nba.v_nba_execution_summary AS
SELECT
    a.action_category,
    a.action_code,
    a.channel,
    COUNT(e.execution_id) AS total_executions,
    COUNT(CASE WHEN e.immediate_response = 'Opened' THEN 1 END) AS opened,
    COUNT(CASE WHEN e.immediate_response = 'Clicked' THEN 1 END) AS clicked,
    COUNT(CASE WHEN e.immediate_response = 'Ignored' THEN 1 END) AS ignored,
    ROUND(100.0 * COUNT(CASE WHEN e.immediate_response IN ('Opened', 'Clicked') THEN 1 END) /
        NULLIF(COUNT(e.execution_id), 0), 2) AS engagement_rate
FROM nba.nba_action_execution e
JOIN nba.nba_action_catalog a ON e.action_id = a.action_id
GROUP BY a.action_category, a.action_code, a.channel;
